#Settingup server port
server:
  port: 9090
  servlet:
    context-path: /payment


spring:
  application:
    name: RazorPayDemo
  #Database Configuration

  thymeleaf:
    cache: false
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/razorPay
    username: postgres
    password: password
    #setting default schema
    hikari:
      schema: payment_schema

  #Jpa Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
        '[use_sql_comments]': true
    hibernate:
      ddl-auto: update
    show-sql: true

###------------------Security Specific Properties-------
razorpay:
  key:
    id: rzp_test_Go0qYBRqU6LOnP

  secret:
    key: ${KEY}
#    key: zzxvIz1wXt85Rlyd2AgEYVsW

#jwt:
#  secret:
#    key: f7bc6a8464fe149289acb79a34d4bc3c7ade068606c4fd7a43a0160833ed20fd
#    validity: 3600000